- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/cooka/detachable_joint/attach"
  gz_topic_name: "/cooka/detachable_joint/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_topic_name: "/cooka/detachable_joint/detach"
  gz_topic_name: "/cooka/detachable_joint/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ